version: '3.8'
services:
  mysql:
    image: 'mysql'
    volumes:
      - data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3310:3310"
    env_file:
      - ./env/mysql.env
  backend:
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    env_file:
      - ./env/back.env
    depends_on:
      - mysql
  frontend:
    build: ./front
    ports:
      -  '8080:8080'
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty:  true
    depends_on:
      - backend
volumes:
  data: